package com.dam.framework.mapping;

import java.lang.reflect.Field;

import com.dam.framework.annotations.GeneratedValue;
import com.dam.framework.annotations.GenerationType;

public record ColumnMetadata(
                Field field,
                String columnName,
                Class<?> javaType,
                String sqlType,
                boolean nullable,
                boolean unique) {

        /**
         * Check if this column has auto-generated values.
         * 
         * @return true if the field is annotated with @GeneratedValue
         */
        public boolean isAutoGenerated() {
                return field.isAnnotationPresent(GeneratedValue.class);
        }

        /**
         * Get the generation strategy for this column.
         * 
         * @return the GenerationType, or null if not auto-generated
         */
        public GenerationType getGenerationStrategy() {
                if (!isAutoGenerated()) {
                        return null;
                }
                return field.getAnnotation(GeneratedValue.class).strategy();
        }
}
