package com.dam.framework.mapping;

import java.sql.Connection;

import com.dam.framework.dialect.Dialect;

/**
 * ID generator for database identity columns (AUTO_INCREMENT, IDENTITY).
 * <p>
 * This strategy relies on the database to generate IDs automatically.
 * The generated ID is retrieved after INSERT using JDBC's getGeneratedKeys().
 * 
 * <p>
 * <b>Supported by:</b>
 * </p>
 * <ul>
 * <li>MySQL: AUTO_INCREMENT</li>
 * <li>SQL Server: IDENTITY</li>
 * <li>PostgreSQL: SERIAL, IDENTITY (since PostgreSQL 10)</li>
 * </ul>
 */
public class IdentityGenerator implements IdGenerator {

  @Override
  public Object generate(Connection connection, Dialect dialect, EntityMetadata metadata) {
    // Identity generation happens in database, no pre-generation needed
    return null;
  }

  @Override
  public boolean isPostInsertGenerator() {
    // ID is generated by database AFTER insert
    return true;
  }
}
