package com.dam.framework.mapping;

import java.sql.Connection;

import com.dam.framework.dialect.Dialect;

/**
 * Strategy interface for generating primary key values.
 * <p>
 * Implements the Strategy Pattern to support different ID generation
 * approaches:
 * <ul>
 * <li>IDENTITY: Database auto-increment</li>
 * <li>SEQUENCE: Database sequences</li>
 * <li>UUID: Application-generated UUIDs</li>
 * <li>TABLE: Table-based key generation</li>
 * </ul>
 * 
 * @see com.dam.framework.annotations.GenerationType
 */
public interface IdGenerator {

  /**
   * Generate a new ID value.
   * 
   * @param connection the database connection
   * @param dialect    the database dialect
   * @param metadata   the entity metadata
   * @return the generated ID value
   */
  Object generate(Connection connection, Dialect dialect, EntityMetadata metadata);

  /**
   * Check if this generator requires retrieving the ID after insert.
   * <p>
   * Returns true for IDENTITY strategy (database generates ID),
   * false for UUID/TABLE (application generates ID before insert).
   * 
   * @return true if ID is generated by database
   */
  boolean isPostInsertGenerator();
}
